### ISSUE TITLE
Project is being sunset

### ISSUE THREAD

**Issue by vreynolds** [honeycombio/prom2hny#5]
See [OSS lifecycle and practices](https://github.com/honeycombio/home/blob/main/honeycomb-oss-lifecycle-and-practices.md)

This project has outlived its useful lifespan, and will be archived in the future. We recommend using the [prometheus receiver](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/prometheusreceiver) with OpenTelemetry to send Prometheus metrics to Honeycomb.

If you are actively using `prom2hny`, please comment on this issue with your use case.

**Comment by MikeGoldsmith** [comment]
Closing #10
